services:
  api:
    build: .
    entrypoint: uvicorn
    command: "--host 0.0.0.0 --reload --workers 1 bbb.api:api"
    volumes:
      - '.:/usr/src'
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - redpanda

  vote_processor_1:
    build: .
    entrypoint: faust
    command: "-A bbb.vote_processor worker --web-port=6060"
    volumes:
      - '.:/usr/src'
    ports:
      - 6060:6060
    env_file:
      - .env
    depends_on:
      - redpanda

  vote_processor_2:
    build: .
    entrypoint: faust
    command: "-A bbb.vote_processor worker --web-port=6061"
    volumes:
      - '.:/usr/src'
    ports:
      - 6061:6061
    env_file:
      - .env
    depends_on:
      - redpanda

  redpanda:
    image: vectorized/redpanda:v22.1.10
    container_name: redpanda
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr 0.0.0.0:9092
      - --advertise-kafka-addr redpanda:9092
    ports:
      - 9092:9092
